### Recuperar todas las noticias
GET http://localhost:8080/noticias

### Recuperar una noticia por id
GET http://localhost:8080/noticias/3

### Recuperar todas las noticias por categoria
GET http://localhost:8080/noticias/categoria?categoria=salud

### Crear una película con POST
POST http://localhost:8080/noticias
Content-Type: application/json

{
  "id": 12,
  "autor": "Matias",
  "categoria": "TEST",
  "copete": "TEST",
  "imagenUrl": "TEST",
  "titulo": "TEST"
}

### Recuperar una noticia por id
GET http://localhost:8080/noticias/12

### Crear una película con POST
PUT http://localhost:8080/noticias/12
Content-Type: application/json

{
  "autor": "Matias",
  "categoria": "TEST2",
  "copete": "TEST2",
  "imagenUrl": "TEST2",
  "titulo": "TEST2"
}

### Recuperar una noticia por id
GET http://localhost:8080/noticias/12

### Borrar noticias por id
DELETE  http://localhost:8080/noticias/12
