### Recuperar todas las noticias
GET https://grupo9api.up.railway.app:3307/noticias/
### Recuperar todas las noticias LOCAL
GET http://localhost:8080/noticias/
### Recuperar una noticia por id
GET https://grupo9api.up.railway.app:3307/noticias/3
### Recuperar una noticia por id LOCAL
GET http://localhost:8080/noticias/3
### Postear una noticia
POST http://localhost:8080/noticias
Content-Type: application/json

{
  "categoria": "1",
  "titulo": "title",
  "cuerpo": "<p>Cuerpo</p>",
  "autor": "Matias",
  "fecha": "2024-06-23",
  "imagen": "https://grupo9.vercel.app/images/noticia1.mobile.webp"

}

### Actualizar una noticia
PATCH http://localhost:8080/noticias/20
Content-Type: application/json

{
  "categoria": "2",
  "titulo": "title2",
  "cuerpo": "<p>Cuerpo2</p>",
  "autor": "Matias2",
  "fecha": "2024-06-24",
  "imagen": "https://grupo9.vercel.app/images/noticia2.mobile.webp"
}

### Borrar una noticia por id
DELETE  https://grupo9api.up.railway.app/noticias/

